### ISSUE TITLE
Monitoring Backup State of VMs 

### ISSUE THREAD

**Issue by HLAGCoding** [WAdama/nas_ab_status#6] opened 2021-03-29 13:56 UTC
Hi,
thanks for the scripts.
We are successfully monitoring the Backup Status of Clients which are in the "PC" and "Physical Server" Group of Active Backup for Business.

Once adding a new sensor which is using the Task List of the "Virtual Machine" Group it fails with "No result or error in XML response" in PRTG.

Error Logging
<?xml version="10.0" encoding="UTF-8" ?><prtg>
/var/prtg/scriptsxml/nas_ab_status_m.sh: line 22: [: too many arguments
/var/prtg/scriptsxml/nas_ab_status_m.sh: line 32: 1617003892 2|11|VM|70915194880|1617000491|1617001668 2|12|VM1|47917826048|1617001670|1617002639 2|13|VM02|28607250432|1617002640|1617003470 2|14|VM02|50050629632|1617003471|1617004533 2|15|VM05|30224154624|1617003893|1617004610 - 1617000491: syntax error in expression (error token is "2|11|VM01|70915194880|1617000491|1617001668 2|12|VM04|47917826048|1617001670|1617002639 2|13|VM06|28607250432|1617002640|1617003470 2|14|VM07|50050629632|1617003471|1617004533 2|15|V3820008|30224154624|1617003893|1617004610 - 1617000491")
<text>Task VM_BACKUP: VM01 VM02</text></prtg>

best

**Comment by WAdama** [comment] 2021-03-29 17:14
Hi,

I have some questions to be sure about the script used and the configuration:
You're using the latest version?
The config file is constructed as described in the readme?
The VMS are all in the same task?
Is one of the VM names containing special characters?

Best regards
Ingo

**Comment by HLAGCoding** [comment] 2021-03-31 15:31
Hi,

thanks for your comment! I will collect the necessary details and get back in this Thread soon. (busy times)

Cheers
HLAGCoding

**Comment by HLAGCoding** [comment] 2021-04-01 12:14
Hi,

**Using v1.0.3**
![image](https://user-images.githubusercontent.com/81571845/113291540-786c3e00-92f3-11eb-9bd5-9ac1216a2070.png)

**Configuration File**
![image](https://user-images.githubusercontent.com/81571845/113291858-f03a6880-92f3-11eb-8ba3-029fa67af624.png)

**PRTG Sensor**
![image](https://user-images.githubusercontent.com/81571845/113291677-a5205580-92f3-11eb-90e6-0aebdd49f9cc.png)

**ABB Task**
![image](https://user-images.githubusercontent.com/81571845/113291753-c4b77e00-92f3-11eb-9b65-56dcd2244f2d.png)

**PRTG Logs**
<?xml version="10.0" encoding="UTF-8" ?><prtg>
/var/prtg/scriptsxml/nas_ab_status_VM_TEST.sh: line 22: [: too many arguments
/var/prtg/scriptsxml/nas_ab_status_VM_TEST.sh: line 32: 1617242628 2|2|V2990004|8052998144|1617242402|1617242590 2|3|V2990005|1358577664|1617242590|1617242669 2|4|V2990007|105939730432|1617242628|1617243615 - 1617242402: syntax error in expression (error token is "2|2|V2990004|8052998144|1617242402|1617242590 2|3|V2990005|1358577664|1617242590|1617242669 2|4|V2990007|105939730432|1617242628|1617243615 - 1617242402")
<text>Task VM_BACKUP: A999V001 V2990004</text></prtg>

**Comment by WAdama** [comment] 2021-04-01 17:19
I can't really see what the problem is...
Can you start the script manually in the bash console? Maybe the output there tell us more than the PRTG log.

Maybe it's just a feeling but how do you created the script on your Syno?

**Comment by HLAGCoding** [comment] 2021-04-06 12:24
Output when running the Script from the console:

![image](https://user-images.githubusercontent.com/81571845/113710086-8fd86c00-96e3-11eb-883d-8a78dd08389d.png)

I have no Internet Access from the Synology, so i created an empty file and copied the source code manually via Clipboard into vi.

**Comment by WAdama** [comment] 2021-04-06 12:28
Then should it be correct, I thought at first about CRLF at line end.

But your screenshot may show the problem: It can't open the SQLite database file.

Did you run the script with sudo? The database file can only be accessed with root access.

**Comment by HLAGCoding** [comment] 2021-04-06 13:18
Sry forgot to use sudo.

![image](https://user-images.githubusercontent.com/81571845/113716927-5c99db00-96eb-11eb-8b57-d699d519f84a.png)

**Comment by WAdama** [comment] 2021-04-06 13:43
I have no really clue what's going wrong in your case. I know from another guy here that the script is working correct. Maybe it's the way you created the script.

Can you download the script via "Code" "Download as zip" and try with the script from the downloaded zip?

**Comment by HLAGCoding** [comment] 2021-04-06 14:07
I have now given temporary Internet access to the NAS. Once i try to download it via wget it throws an 404 Error

![image](https://user-images.githubusercontent.com/81571845/113723963-2a3fac00-96f2-11eb-84a7-fcb1dc22f0e0.png)

**Comment by WAdama** [comment] 2021-04-06 14:10
Just saw: There's an error with the URL. It has to be
wget https://raw.githubusercontent.com/WAdama/nas_ab_status/master/nas_ab_status_m.sh

**Comment by HLAGCoding** [comment] 2021-04-06 14:11
Just noticed it needs to be
https://github.com/WAdama/nas_ab_status/blob/master/nas_ab_status_m.sh

**Comment by WAdama** [comment] 2021-04-06 14:15
I've already corrected it...

**Comment by HLAGCoding** [comment] 2021-04-06 14:27
Great thanks, unfortunately no change with the new Script.
Exact outcome as in Post:  https://github.com/WAdama/nas_ab_status/issues/6#issuecomment-814112985

I am able to monitor the ABB status of the VMs with the old version 1.0.2 of the script.

**Comment by WAdama** [comment] 2021-04-06 14:33
Do you have added the task name to the config file?
It should like this:
DEVICES=(Device1 Device2 Server1 Server2)
TASK=Task1

**Comment by HLAGCoding** [comment] 2021-04-06 16:44
Found the issue...
The Taskname in Synology is named: VM_BACKUP
Have renamed the Task in ABB and in the .conf to VMBACKUP and its working as expected!

**Comment by WAdama** [comment] 2021-04-06 16:49
I asked about special characters [https://github.com/WAdama/nas_ab_status/issues/6#issuecomment-809554852](url), but I have to admit, an underscore I didn't had in mind... :-)

You could also set the names in quotation marks...

I will changed the description...

**Comment by HLAGCoding** [comment] 2021-04-06 16:54
I thought special characters are not allowed for the Device Name but also for the Tasks: good to know!
Thanks for the support and for the script. Will now roll it out to 70+ Synology NAS Systems :-)

**Comment by WAdama** [comment] 2021-04-06 16:55
You're quite welcome...

I learn with each issue...

By the way: Then please close this one... ;-)

**Closed as completed** 2021-04-06 16:57 UTC
Labels: help wanted

**Comment by HLAGCoding** [comment] 2021-04-06 16:58
Closing issue as its fixed.
Issue was a special character in the Task Name
